<?php

class Contact extends DataObject{
	private static $db = array(
		'OwnerLastName' => 'Varchar',
		'OwnerFirstName' => 'Varchar',
		'OwnerMiddleName' => 'Varchar',
		'OwnerDateOfDeath' => 'Varchar',
		'OwnerCurrentAge' => 'Varchar',
		'OwnerMiddleName' => 'Varchar',
		'OwnerBusinessName' => 'Varchar',
		'Deceased' => 'Varchar',
		'TloAddress1Line1' = 'Varchar',
		'TloAddress1City' = 'Varchar',
		'TloAddress1State' = 'Varchar',
		'TloAddress1Zip' = 'Varchar',
		'TloAddress1DateFirstSeen' = 'Varchar',
		'TloAddress1DateLastSeen' = 'Varchar',
		'TloAddress2Line1' = 'Varchar',
		'TloAddress2City' = 'Varchar',
		'TloAddress2State' = 'Varchar',
		'TloAddress2Zip' = 'Varchar',
		'TloAddress2DateFirstSeen' = 'Varchar',
		'TloAddress2DateLastSeen' = 'Varchar',
		'TloAddress3Line1' = 'Varchar',
		'TloAddress3City' = 'Varchar',
		'TloAddress3State' = 'Varchar',
		'TloAddress3Zip' = 'Varchar',
		'TloAddress3DateFirstSeen' = 'Varchar',
		'TloAddress3DateLastSeen' = 'Varchar',
		'TloPhone1' = 'Varchar',
		'TloPhone1OutboundAttempts' => 'Int',
		'TloPhone1InboundAttempts' => 'Int',
		'TloPhone1PhoneType' = 'Varchar',
		'TloPhone2' = 'Varchar',
		'TloPhone2OutboundAttempts' => 'Int',
		'TloPhone2InboundAttempts' => 'Int',
		'TloPhone2PhoneType' = 'Varchar',
		'TloPhone3' = 'Varchar',
		'TloPhone3OutboundAttempts' => 'Int',
		'TloPhone3InboundAttempts' => 'Int',
		'TloPhone3PhoneType' = 'Varchar',
		'TloPhone4' = 'Varchar',
		'TloPhone4OutboundAttempts' => 'Int',
		'TloPhone4InboundAttempts' => 'Int',
		'TloPhone4PhoneType' = 'Varchar',
		'TloPhone5' = 'Varchar',
		'TloPhone5OutboundAttempts' => 'Int',
		'TloPhone5InboundAttempts' => 'Int',
		'TloPhone5PhoneType' = 'Varchar',
		'TloPhone6' = 'Varchar',
		'TloPhone6utboundAttempts' => 'Int',
		'TloPhone6InboundAttempts' => 'Int',
		'TloPhone6PhoneType' = 'Varchar',
		'TloPhone7' = 'Varchar',
		'TloPhone7OutboundAttempts' => 'Int',
		'TloPhone7InboundAttempts' => 'Int',
		'TloPhone7PhoneType' = 'Varchar',
		'TloPhone8' = 'Varchar',
		'TloPhone8OutboundAttempts' => 'Int',
		'TloPhone8InboundAttempts' => 'Int',
		'TloPhone8PhoneType' = 'Varchar',
		'TloPhone9' = 'Varchar',
		'TloPhone9OutboundAttempts' => 'Int',
		'TloPhone9InboundAttempts' => 'Int',
		'TloPhone9PhoneType' = 'Varchar',
		'TloPhone10' = 'Varchar',
		'TloPhone10OutboundAttempts' => 'Int',
		'TloPhone10InboundAttempts' => 'Int',
		'TloPhone10PhoneType' = 'Varchar',
		'TloRelatives1DateOfBirth' = 'Varchar',
		'TloRelatives1FirstName' = 'Varchar',
		'TloRelatives1MiddleName' = 'Varchar',
		'TloRelatives1LastName' = 'Varchar',
		'TloRelatives1NameSuffix' = 'Varchar',
		'TloRelatives1Phone' = 'Varchar',
		'TloRelatives1PhoneOutboundAttempts' => 'Int',
		'TloRelatives1PhoneInboundAttempts' => 'Int',
		'TloRelatives1AddressLine1' = 'Varchar',
		'TloRelatives1City' = 'Varchar',
		'TloRelatives1Zip' = 'Varchar',
		'TloRelatives2DateOfBirth' = 'Varchar',
		'TloRelatives2FirstName' = 'Varchar',
		'TloRelatives2MiddleName' = 'Varchar',
		'TloRelatives2LastName' = 'Varchar',
		'TloRelatives2NameSuffix' = 'Varchar',
		'TloRelatives2Phone' = 'Varchar',
		'TloRelatives2PhoneOutboundAttempts' => 'Int',
		'TloRelatives2PhoneInboundAttempts' => 'Int',
		'TloRelatives2AddressLine1' = 'Varchar',
		'TloRelatives2City' = 'Varchar',
		'TloRelatives2Zip' = 'Varchar',
		'TloRelatives3DateOfBirth' = 'Varchar',
		'TloRelatives3FirstName' = 'Varchar',
		'TloRelatives3MiddleName' = 'Varchar',
		'TloRelatives3LastName' = 'Varchar',
		'TloRelatives3NameSuffix' = 'Varchar',
		'TloRelatives3Phone' = 'Varchar',
		'TloRelatives3PhoneOutboundAttempts' => 'Int',
		'TloRelatives3PhoneInboundAttempts' => 'Int',
		'TloRelatives3AddressLine1' = 'Varchar',
		'TloRelatives3City' = 'Varchar',
		'TloRelatives3Zip' = 'Varchar',
		'TloRelatives4DateOfBirth' = 'Varchar',
		'TloRelatives4FirstName' = 'Varchar',
		'TloRelatives4MiddleName' = 'Varchar',
		'TloRelatives4LastName' = 'Varchar',
		'TloRelatives4NameSuffix' = 'Varchar',
		'TloRelatives4Phone' = 'Varchar',
		'TloRelatives4PhoneOutboundAttempts' => 'Int',
		'TloRelatives4PhoneInboundAttempts' => 'Int',
		'TloRelatives4AddressLine1' = 'Varchar',
		'TloRelatives4City' = 'Varchar',
		'TloRelatives4Zip' = 'Varchar',
		'TloRelatives5DateOfBirth' = 'Varchar',
		'TloRelatives5FirstName' = 'Varchar',
		'TloRelatives5MiddleName' = 'Varchar',
		'TloRelatives5LastName' = 'Varchar',
		'TloRelatives5NameSuffix' = 'Varchar',
		'TloRelatives5Phone' = 'Varchar',
		'TloRelatives5PhoneOutboundAttempts' => 'Int',
		'TloRelatives5PhoneInboundAttempts' => 'Int',
		'TloRelatives5AddressLine1' = 'Varchar',
		'TloRelatives5City' = 'Varchar',
		'TloRelatives5Zip' = 'Varchar',
		);

	private static $defaults = array(
		'TloPhone1OutboundAttempts' => 0,
		'TloPhone1InboundAttempts' => 'Int',
		'TloPhone2OutboundAttempts' => 0,
		'TloPhone2InboundAttempts' => 'Int',
		'TloPhone3OutboundAttempts' => 0,
		'TloPhone3InboundAttempts' => 'Int',
		'TloPhone4OutboundAttempts' => 0,
		'TloPhone4InboundAttempts' => 'Int',
		'TloPhone5OutboundAttempts' => 0,
		'TloPhone5InboundAttempts' => 'Int',
		'TloPhone6OutboundAttempts' => 0,
		'TloPhone6InboundAttempts' => 'Int',
		'TloPhone7OutboundAttempts' => 0,
		'TloPhone7InboundAttempts' => 'Int',
		'TloPhone8OutboundAttempts' => 0,
		'TloPhone8InboundAttempts' => 'Int',
		'TloPhone9OutboundAttempts' => 0,
		'TloPhone9InboundAttempts' => 'Int',
		'TloPhone10OutboundAttempts' => 0,
		'TloPhone10InboundAttempts' => 'Int',
		'TloRelatives1PhoneOutboundAttempts' => 0,
		'TloRelatives1PhoneInboundAttempts' => 'Int',
		'TloRelatives2PhoneOutboundAttempts' => 0,
		'TloRelatives2PhoneInboundAttempts' => 'Int',
		'TloRelatives3PhoneOutboundAttempts' => 0,
		'TloRelatives3PhoneInboundAttempts' => 'Int',
		'TloRelatives4PhoneOutboundAttempts' => 0,
		'TloRelatives4PhoneInboundAttempts' => 'Int',
		'TloRelatives5PhoneOutboundAttempts' => 0,
		'TloRelatives5PhoneInboundAttempts' => 'Int',
	);

	private static $has_many = array(
		'PrimaryParcels' => 'Parcel.PrimaryContact'
	);

	private static $belongs_many_many = array(
		'RelativeParcels' => 'Parcel'
	);
	
	static $api_access = true;
	
	
	
    
	/*static $searchable_fields = array(
    //"DistrictID",
    );*/ 
    
	public function getCMSFields()
	{
	    $fields = parent::getCMSFields();
		return $fields;
	}

}